import type { FixtureState, GitHubSettingRecord, LoopRegistryItem } from "@/lib/types";

export const portalFixture: FixtureState = {
  repos: [
    {
      name: "loopworks-web",
      owner: "ncolesummers",
      description: "Operator portal for repo intake, approvals, and deploy visibility.",
      health: "healthy",
      milestone: "M1",
      area: "design-system",
      priority: "p0",
      openIssues: 14,
      staleDays: 1,
      lastSynced: "2m ago",
    },
    {
      name: "factory-core",
      owner: "ncolesummers",
      description: "Loop engine, issue ingestion, and durable execution history.",
      health: "watch",
      milestone: "M3",
      area: "loop-mvp",
      priority: "p0",
      openIssues: 27,
      staleDays: 4,
      lastSynced: "8m ago",
    },
    {
      name: "integration-playground",
      owner: "ncolesummers",
      description: "Sandbox repo used to exercise GitHub and Vercel sync paths.",
      health: "blocked",
      milestone: "M2",
      area: "github",
      priority: "p1",
      openIssues: 6,
      staleDays: 9,
      lastSynced: "17m ago",
    },
  ],
  deployments: [
    {
      name: "preview/portal-shell",
      state: "preview",
      environment: "preview",
      branch: "codex/m1-shell",
      sha: "8f2c1c4",
      url: "https://loopworks-git-codex-m1-shell.vercel.app",
      age: "12m",
      checks: ["Lint passed", "Playwright passed", "A11y baseline"],
    },
    {
      name: "main",
      state: "success",
      environment: "production",
      branch: "main",
      sha: "7ad2f90",
      url: "https://loopworks.vercel.app",
      age: "1h",
      checks: ["Build passed", "Typecheck passed", "Deploy ready"],
    },
    {
      name: "feature/github-sync",
      state: "queued",
      environment: "preview",
      branch: "feature/github-sync",
      sha: "c1b9ae8",
      url: "pending",
      age: "4m",
      checks: ["Waiting for upload", "Awaiting preview URL"],
    },
  ],
  loops: [
    {
      name: "Intake and triage",
      state: "Triage",
      enabled: true,
      owner: "Avery",
      queueDepth: 4,
      risk: "low",
    },
    {
      name: "Implementation routing",
      state: "In Progress",
      enabled: true,
      owner: "Morgan",
      queueDepth: 7,
      risk: "medium",
    },
    {
      name: "Review gate",
      state: "Waiting on Review",
      enabled: false,
      owner: "Security",
      queueDepth: 2,
      risk: "high",
    },
  ] satisfies LoopRegistryItem[],
  timeline: [
    {
      kind: "sync",
      at: "09:14",
      actor: "GitHub webhook",
      title: "Issue sync completed",
      detail: "Fetched 38 issues, 12 labels, and 4 milestone changes for loop hydration.",
    },
    {
      kind: "state",
      at: "09:31",
      actor: "Builder agent",
      title: "Loop moved to In Progress",
      detail: "Issue #214 advanced after repo selection and scope confirmation.",
    },
    {
      kind: "artifact",
      at: "09:42",
      actor: "Vercel",
      title: "Preview deployed",
      detail: "New shell preview passed lint and smoke tests.",
      artifact: "Preview URL",
    },
    {
      kind: "approval",
      at: "10:02",
      actor: "Maintainer",
      title: "Approval requested",
      detail: "Security review gate is waiting on redaction confirmation and repo access checks.",
    },
  ],
  artifacts: [
    {
      label: "Preview URL",
      href: "https://loopworks-git-codex-m1-shell.vercel.app",
      detail: "Vercel preview for the latest dashboard shell fixture.",
      state: "available",
      kind: "preview",
    },
    {
      label: "Validation report",
      href: "https://github.com/ncolesummers/loopworks/actions",
      detail: "Deterministic checks captured before reviewer signoff.",
      state: "available",
      kind: "validation",
    },
    {
      label: "Security review notes",
      href: "https://github.com/ncolesummers/loopworks/issues/23",
      detail: "Pending approval notes for the high-risk write-path review.",
      state: "pending",
      kind: "review",
    },
  ],
  validationResults: [
    {
      name: "Typecheck",
      command: "bun run typecheck",
      status: "passed",
      duration: "18s",
      detail: "Strict TypeScript completed without emitting.",
      artifactHref: "https://github.com/ncolesummers/loopworks/actions",
    },
    {
      name: "Playwright",
      command: "bun run test:e2e",
      status: "passed",
      duration: "1m 12s",
      detail: "Portal smoke and axe checks passed in light and dark.",
      artifactHref: "https://github.com/ncolesummers/loopworks/actions",
    },
    {
      name: "Storybook a11y",
      command: "bun run storybook:build",
      status: "warning",
      duration: "42s",
      detail: "Component review is ready for manual screenshot baseline approval.",
    },
  ],
  approval: {
    state: "needs-review",
    owner: "Priya",
    due: "Today, 4:00 PM",
    risk: "Token scopes cover GitHub read access and Vercel preview metadata only.",
    checklist: [
      { label: "Session handling is documented", done: true },
      { label: "Repo access is scoped per installation", done: true },
      { label: "Secrets are redacted from summaries", done: true },
      { label: "Write paths require explicit approval", done: false },
    ],
  },
  githubSettings: [
    {
      key: "sso",
      title: "GitHub SSO",
      detail: "Authenticated with org-managed sign-in and local fixture bypass for development.",
      enabled: true,
    },
    {
      key: "webhooks",
      title: "Webhooks",
      detail: "Issue and PR webhooks hydrate the loop registry and deployment snapshots.",
      enabled: true,
    },
    {
      key: "issue-sync",
      title: "Issue sync",
      detail: "Milestones, labels, and comments are mirrored into the operator catalog.",
      enabled: true,
    },
    {
      key: "pr-sync",
      title: "PR sync",
      detail: "Pull request checks and review status are visible before merge gating.",
      enabled: true,
    },
    {
      key: "label-mapping",
      title: "Label mapping",
      detail: "Milestone, priority, and area labels map to loop states and ownership.",
      enabled: true,
    },
    {
      key: "secret-redaction",
      title: "Secret redaction",
      detail: "Tokens and webhook payload fragments stay out of logs and UI summaries.",
      enabled: true,
    },
  ] satisfies GitHubSettingRecord[],
};
