import type { FixtureState, GitHubSettingRecord, LoopRegistryItem } from "@/lib/types";

export const portalFixture: FixtureState = {
  repos: [
    {
      name: "loopworks-web",
      owner: "ncolesummers",
      description: "Operator portal for repo intake, approvals, and deploy visibility.",
      health: "healthy",
      githubHref: "https://github.com/ncolesummers/loopworks-web",
      framework: "Next.js",
      defaultBranch: "main",
      ciCommands: ["bun run validate", "bun run build"],
      docsHref: "https://github.com/ncolesummers/loopworks/tree/main/docs",
      observabilityHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/observability.md",
      designSystemHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/design-review-checklist.md",
      enabledLoops: ["Intake and triage", "Implementation routing"],
      validationGates: ["Typecheck", "Playwright", "Storybook"],
      vercelProjectId: "prj_loopworks",
      vercelProjectHref: "https://vercel.com/ncolesummers/loopworks",
      milestone: "M1",
      area: "design-system",
      priority: "p0",
      openIssues: 14,
      staleDays: 1,
      lastSynced: "2m ago",
    },
    {
      name: "factory-core",
      owner: "ncolesummers",
      description: "Loop engine, issue ingestion, and durable execution history.",
      health: "watch",
      githubHref: "https://github.com/ncolesummers/factory-core",
      framework: "Bun + Drizzle",
      defaultBranch: "main",
      ciCommands: ["bun run test", "bun run typecheck"],
      docsHref: "https://github.com/ncolesummers/loopworks/blob/main/docs/loop-manifest.md",
      observabilityHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/observability.md",
      designSystemHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/design-review-checklist.md",
      enabledLoops: ["Implementation routing"],
      validationGates: ["Unit tests", "Webhook idempotency", "Logger redaction"],
      vercelProjectId: "prj_factory_core",
      vercelProjectHref: "https://vercel.com/ncolesummers/factory-core",
      milestone: "M3",
      area: "loop-mvp",
      priority: "p0",
      openIssues: 27,
      staleDays: 4,
      lastSynced: "8m ago",
    },
    {
      name: "delivery-ops",
      owner: "ncolesummers",
      description: "Blocked deployment workflow catalog fixture for gate and loop visibility.",
      health: "blocked",
      githubHref: "https://github.com/ncolesummers/delivery-ops",
      framework: "Next.js",
      defaultBranch: "main",
      ciCommands: ["bun run validate", "bun run test:e2e"],
      docsHref: "https://github.com/ncolesummers/loopworks/blob/main/docs/prd.md",
      observabilityHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/observability.md",
      designSystemHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/design-review-checklist.md",
      enabledLoops: ["Review gate"],
      validationGates: ["Playwright", "Storybook"],
      vercelProjectId: "prj_delivery_ops",
      vercelProjectHref: "https://vercel.com/ncolesummers/delivery-ops",
      milestone: "M2",
      area: "catalog",
      priority: "p0",
      openIssues: 3,
      staleDays: 6,
      lastSynced: "14m ago",
    },
    {
      name: "integration-playground",
      owner: "ncolesummers",
      description: "Sandbox repo used to exercise GitHub and Vercel sync paths.",
      health: "disconnected",
      githubHref: "https://github.com/ncolesummers/integration-playground",
      framework: "Fixture",
      defaultBranch: "main",
      ciCommands: ["bun run test:e2e"],
      docsHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/personas-and-test-scenarios.md",
      observabilityHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/observability.md",
      designSystemHref:
        "https://github.com/ncolesummers/loopworks/blob/main/docs/design-review-checklist.md",
      enabledLoops: [],
      validationGates: ["Fixture fallback check"],
      milestone: "M2",
      area: "github",
      priority: "p1",
      openIssues: 6,
      staleDays: 9,
      lastSynced: "17m ago",
    },
  ],
  deployments: [
    {
      name: "preview/portal-shell",
      state: "ready",
      environment: "preview",
      branch: "codex/m1-shell",
      sha: "8f2c1c4",
      url: "https://loopworks-git-codex-m1-shell.vercel.app",
      age: "12m",
      checks: ["Preview ready", "Playwright passed", "A11y baseline"],
      inspectorUrl: "https://vercel.com/ncolesummers/loopworks/dpl_preview_shell",
    },
    {
      name: "production/main",
      state: "ready",
      environment: "production",
      branch: "main",
      sha: "7ad2f90",
      url: "https://loopworks.vercel.app",
      age: "1h",
      checks: ["Build ready", "Runtime logs clean"],
      inspectorUrl: "https://vercel.com/ncolesummers/loopworks/dpl_prod",
    },
    {
      name: "preview/building",
      state: "building",
      environment: "preview",
      branch: "codex/9-vercel-deploy",
      sha: "pending",
      age: "Queued",
      checks: ["Build started"],
    },
    {
      name: "preview/errored",
      state: "error",
      environment: "preview",
      branch: "codex/failed-preview",
      sha: "badc0de",
      url: "https://loopworks-git-failed.vercel.app",
      age: "3m",
      checks: ["Build failed"],
      inspectorUrl: "https://vercel.com/ncolesummers/loopworks/dpl_error",
    },
    {
      name: "preview/queued",
      state: "queued",
      environment: "preview",
      branch: "feature/github-sync",
      sha: "c1b9ae8",
      age: "4m",
      checks: ["Waiting for upload", "Awaiting preview URL"],
    },
  ],
  loops: [
    {
      name: "Intake and triage",
      state: "Triage",
      enabled: true,
      owner: "Avery",
      queueDepth: 4,
      risk: "low",
    },
    {
      name: "Implementation routing",
      state: "In Progress",
      enabled: true,
      owner: "Morgan",
      queueDepth: 7,
      risk: "medium",
    },
    {
      name: "Review gate",
      state: "Waiting on Review",
      enabled: false,
      owner: "Security",
      queueDepth: 2,
      risk: "high",
    },
  ] satisfies LoopRegistryItem[],
  timeline: [
    {
      kind: "planning",
      at: "09:14",
      actor: "Planning agent",
      title: "Planning",
      detail: "Created an executable plan artifact linked to Issue #19 and persona IDs.",
      artifact: "Plan artifact",
    },
    {
      kind: "test",
      at: "09:21",
      actor: "Builder agent",
      title: "Test writing",
      detail: "Added failing Vitest and Playwright coverage before production changes.",
      artifact: "Red tests",
    },
    {
      kind: "development",
      at: "09:35",
      actor: "Builder agent",
      title: "Development",
      detail: "Implemented the smallest green path for typed fixtures and workflow surfaces.",
      artifact: "Patch",
    },
    {
      kind: "validation",
      at: "09:48",
      actor: "CI runner",
      title: "Validation",
      detail: "Deterministic checks completed before review or PR judgment.",
      artifact: "Validation report",
    },
    {
      kind: "review",
      at: "09:54",
      actor: "Reviewer",
      title: "Code review",
      detail: "Reviewer checks evidence, Vercel preview, and source issue linkage.",
      artifact: "Review notes",
    },
    {
      kind: "commit",
      at: "10:01",
      actor: "Maintainer",
      title: "Commit",
      detail: "Validated changes are ready for an atomic conventional commit.",
      artifact: "Commit intent",
    },
    {
      kind: "pull_request",
      at: "10:08",
      actor: "Maintainer",
      title: "PR created",
      detail: "PR intent links source issue, run evidence, and Vercel preview context.",
      artifact: "PR intent",
    },
    {
      kind: "done",
      at: "10:14",
      actor: "Maintainer",
      title: "Done",
      detail: "Run closes only after deterministic validation and review evidence are present.",
    },
  ],
  artifacts: [
    {
      label: "Preview URL",
      href: "https://loopworks-git-codex-m1-shell.vercel.app",
      detail: "Vercel preview for the latest dashboard shell fixture.",
      state: "available",
      kind: "preview",
    },
    {
      label: "Validation report",
      href: "https://github.com/ncolesummers/loopworks/actions",
      detail: "Deterministic checks captured before reviewer signoff.",
      state: "available",
      kind: "validation",
    },
    {
      label: "Security review notes",
      href: "https://github.com/ncolesummers/loopworks/issues/23",
      detail: "Pending approval notes for the high-risk write-path review.",
      state: "pending",
      kind: "review",
    },
  ],
  validationResults: [
    {
      name: "Typecheck",
      command: "bun run typecheck",
      status: "passed",
      duration: "18s",
      detail: "Strict TypeScript completed without emitting.",
      artifactHref: "https://github.com/ncolesummers/loopworks/actions",
    },
    {
      name: "Playwright",
      command: "bun run test:e2e",
      status: "passed",
      duration: "1m 12s",
      detail: "Portal smoke and axe checks passed in light and dark.",
      artifactHref: "https://github.com/ncolesummers/loopworks/actions",
    },
    {
      name: "Storybook a11y",
      command: "bun run storybook:build",
      status: "warning",
      duration: "42s",
      detail: "Component review is ready for manual screenshot baseline approval.",
    },
  ],
  approval: {
    state: "needs-review",
    owner: "Priya",
    due: "Today, 4:00 PM",
    risk: "Token scopes cover GitHub read access and Vercel preview metadata only.",
    checklist: [
      { label: "Session handling is documented", done: true },
      { label: "Repo access is scoped per installation", done: true },
      { label: "Secrets are redacted from summaries", done: true },
      { label: "Write paths require explicit approval", done: false },
    ],
  },
  githubSettings: [
    {
      key: "sso",
      title: "GitHub SSO",
      detail: "Authenticated with org-managed sign-in and local fixture bypass for development.",
      enabled: true,
    },
    {
      key: "webhooks",
      title: "Webhooks",
      detail: "Issue and PR webhooks hydrate the loop registry and deployment snapshots.",
      enabled: true,
    },
    {
      key: "issue-sync",
      title: "Issue sync",
      detail: "Milestones, labels, and comments are mirrored into the operator catalog.",
      enabled: true,
    },
    {
      key: "pr-sync",
      title: "PR sync",
      detail: "Pull request checks and review status are visible before merge gating.",
      enabled: true,
    },
    {
      key: "label-mapping",
      title: "Label mapping",
      detail: "Milestone, priority, and area labels map to loop states and ownership.",
      enabled: true,
    },
    {
      key: "secret-redaction",
      title: "Secret redaction",
      detail: "Tokens and webhook payload fragments stay out of logs and UI summaries.",
      enabled: true,
    },
  ] satisfies GitHubSettingRecord[],
};
