version: 2

multi-ecosystem-groups:
  monthly-version-updates:
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: monthly
      time: "09:00"
      timezone: America/Los_Angeles

updates:
  - package-ecosystem: bun
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: monthly-version-updates

  - package-ecosystem: github-actions
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: monthly-version-updates
