import type { VercelDeploymentPayload } from "./types";

export const vercelDeploymentFixtures: VercelDeploymentPayload[] = [
  {
    uid: "dpl_fixture_preview_1",
    name: "loopworks",
    projectId: "prj_loopworks",
    url: "loopworks-git-issue-42-loopworks.vercel.app",
    state: "READY",
    readyState: "READY",
    createdAt: Date.parse("2026-06-18T18:05:00.000Z"),
    ready: Date.parse("2026-06-18T18:07:12.000Z"),
    target: "preview",
    alias: ["loopworks-preview-42.vercel.app"],
    inspectorUrl: "https://vercel.com/ncolesummers/loopworks/preview/42",
    creator: {
      username: "eve-agent",
    },
    gitSource: {
      type: "github",
      ref: "issue-42-vercel-preview",
      sha: "abc1234567890def",
      repo: "loopworks",
      org: "ncolesummers",
      prId: 19,
    },
    meta: {
      githubCommitRef: "issue-42-vercel-preview",
      githubCommitSha: "abc1234567890def",
      githubPullRequestId: "19",
      loopworksIssue: "42",
    },
  },
  {
    uid: "dpl_fixture_prod_1",
    name: "loopworks",
    projectId: "prj_loopworks",
    url: "loopworks.vercel.app",
    state: "READY",
    readyState: "READY",
    createdAt: Date.parse("2026-06-18T20:10:00.000Z"),
    ready: Date.parse("2026-06-18T20:12:45.000Z"),
    target: "production",
    alias: ["loopworks.vercel.app"],
    inspectorUrl: "https://vercel.com/ncolesummers/loopworks/dpl_prod",
    creator: {
      username: "ncolesummers",
    },
    gitSource: {
      type: "github",
      ref: "main",
      sha: "fedcba0987654321",
      repo: "loopworks",
      org: "ncolesummers",
    },
    meta: {
      githubCommitRef: "main",
      githubCommitSha: "fedcba0987654321",
    },
  },
  {
    uid: "dpl_fixture_preview_building",
    name: "loopworks",
    projectId: "prj_loopworks",
    state: "BUILDING",
    readyState: "BUILDING",
    createdAt: Date.parse("2026-06-18T20:20:00.000Z"),
    target: "preview",
    inspectorUrl: "https://vercel.com/ncolesummers/loopworks/dpl_building",
    creator: {
      username: "eve-agent",
    },
    gitSource: {
      type: "github",
      ref: "codex/9-vercel-deploy",
      sha: "pending",
      repo: "loopworks",
      org: "ncolesummers",
      prId: 9,
    },
    meta: {
      githubCommitRef: "codex/9-vercel-deploy",
      githubCommitSha: "pending",
      githubPullRequestId: "9",
      loopworksIssue: "9",
    },
  },
  {
    uid: "dpl_fixture_preview_error",
    name: "loopworks",
    projectId: "prj_loopworks",
    url: "loopworks-git-failed.vercel.app",
    state: "ERROR",
    readyState: "ERROR",
    createdAt: Date.parse("2026-06-18T20:25:00.000Z"),
    target: "preview",
    alias: ["loopworks-git-failed.vercel.app"],
    inspectorUrl: "https://vercel.com/ncolesummers/loopworks/dpl_error",
    creator: {
      username: "eve-agent",
    },
    gitSource: {
      type: "github",
      ref: "codex/failed-preview",
      sha: "badc0de",
      repo: "loopworks",
      org: "ncolesummers",
      prId: 9,
    },
    meta: {
      githubCommitRef: "codex/failed-preview",
      githubCommitSha: "badc0de",
      githubPullRequestId: "9",
      loopworksIssue: "9",
    },
  },
];
